http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  auth:
    host: localhost
    paths: '/auth/*'
  book:
    host: localhost
    paths: '/books/*'
serviceEndpoints:
  auth-service:
    url: 'http://localhost:8000/auth/'
  book-service:
    url: 'http://localhost:8001/books/'
policies:
  - cors
  - log
  - proxy
pipelines:
  auth:
    apiEndpoints:
      - auth
    policies:
      - cors:
          - action:
              origin: false
      - proxy:
          - action:
              serviceEndpoint: auth-service 
              changeOrigin: true
              prependPath: false
      - log:
        - action:
            message: ${req.method} ${req.originalUrl}
  book:
    apiEndpoints:
      - book
    policies:
      - cors:
          - action:
              origin: false
      - proxy:
          - action:
              serviceEndpoint: book-service 
              changeOrigin: true
              prependPath: false
      - log:
        - action:
            message: ${req.method} ${req.originalUrl}
